# kubectl apply -f anghelo-goicochea-07-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: anghelo-goicochea-07-secret
  namespace: anghelo-goicochea-07-namespace
type: Opaque
data:
  DATABASE: bG9zcmV5ZXM=   # en Base64
  URI: bW9uZ29kYitzcnY6Ly9hbmdoZWxvZ29pY29jaGVhX2RiX3VzZXJzOjVCNkI3eGRMRldtSkk1dkZAY2x1c3RlcjAuZmlxMmFqci5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode