# kubectl apply -f nori-cuya-05-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: nori-cuya-05-secret
  namespace: nori-cuya-05-namespace
type: Opaque
data:
  DATABASE: bG9zcmV5ZXM=   # en Base64
  URI: bW9uZ29kYitzcnY6Ly9hbmdoZWxvZ29pY29jaGVhX2RiX3VzZXJzOjVCNkI3eGRMRldtSkk1dkZAY2x1c3RlcjAuZmlxMmFqci5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode